name: oraclelinux8-golang-1.17-ci

on:
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: just build for now
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          context: .
          push: false
          tags: denismakogon/oraclelinux8-golang:1.17
          build-args: |
            OEL_BASE_IMAGE="oraclelinux:8-slim"
            GOLANG_VERSION=1.17
            GO_BINARY_SHA256='6bf89fc4f5ad763871cf7eac80a2d594492de7a818303283f1366a7f6a30372d'
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
